import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import {LuBookOpen as BookOpen, LuUsers as Users, LuClipboardCheck as ClipboardCheck, LuCalendarDays as CalendarDays, LuPlus as Plus, LuUserCheck as UserCheck, LuFileCheck as FileCheck, LuArrowRight as ArrowRight, LuClock as Clock} from "react-icons/lu";
import { useAuth } from "../../context/AuthContext";
import { getTeacherCourses,getTeacherStudents,getPendingReviews,getTeacherClasses } from "../../services/teacherService";
import { TeacherPage,Card,Badge,State,Button,fmtDate,fmtTime } from "../../components/teacher/TeacherUI";

export default function Dashboard(){
 const {user,profile}=useAuth(); const [d,setD]=useState(null); const [error,setError]=useState("");
 useEffect(()=>{let on=true;(async()=>{try{const [courses,students,reviews,classes]=await Promise.all([getTeacherCourses(user.id),getTeacherStudents(user.id),getPendingReviews(user.id),getTeacherClasses(user.id)]);if(on)setD({courses,students,reviews,classes});}catch(e){console.error(e);if(on)setError("We couldn't load your teaching overview.");}})();return()=>{on=false}},[user.id]);
 if(error)return <TeacherPage title="Teacher Dashboard"><State type="error" message={error}/></TeacherPage>;
 if(!d)return <TeacherPage title="Teacher Dashboard"><State/></TeacherPage>;
 const name=profile?.full_name||user.user_metadata?.full_name||"Teacher"; const today=new Date(); const todays=d.classes.filter(c=>new Date(c.starts_at).toDateString()===today.toDateString());
 const stats=[["Total Courses",d.courses.length,BookOpen],["Total Students",new Set(d.students.map(x=>x.student_id)).size,Users],["Pending Reviews",d.reviews.length,ClipboardCheck],["Today's Classes",todays.length,CalendarDays]];
 return <TeacherPage title={`Good ${today.getHours()<12?"morning":today.getHours()<18?"afternoon":"evening"}, ${name.split(" ")[0]} 👋`} subtitle="Here's an overview of your teaching activity.">
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,Icon])=><Card key={label} className="p-5"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></div><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Icon size={21}/></div></div></Card>)}</div>
  <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]">
   <Card><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">Today's Classes</h2><p className="text-xs text-slate-500">Your scheduled teaching sessions</p></div><Link to="/teacher/calendar" className="text-sm font-semibold text-blue-600">View calendar</Link></div><div className="divide-y">{todays.length?todays.map(c=><div key={c.id} className="flex items-center justify-between p-5"><div><p className="font-semibold">{c.title}</p><p className="text-sm text-slate-500">{c.courses?.title||"Course"} · {fmtTime(c.starts_at)}–{fmtTime(c.ends_at)}</p></div><Badge tone={c.status==="live"?"green":"blue"}>{c.status}</Badge></div>):<State type="empty" message="No classes scheduled for today."/>}</div></Card>
   <Card><div className="border-b p-5"><h2 className="font-bold">Quick Actions</h2></div><div className="grid gap-3 p-4">{[[Plus,"Create Assignment","/teacher/assignments"],[Users,"View Students","/teacher/students"],[UserCheck,"Mark Attendance","/teacher/attendance"],[FileCheck,"Review Submissions","/teacher/assignments/review"]].map(([I,l,p])=><Link key={l} to={p} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold hover:border-blue-200 hover:bg-blue-50"><span className="rounded-lg bg-slate-100 p-2 text-slate-600"><I size={17}/></span>{l}<ArrowRight size={16} className="ml-auto text-slate-400"/></Link>)}</div></Card>
  </div>
  <div className="grid gap-6 xl:grid-cols-2">
   <Card><div className="flex items-center justify-between border-b p-5"><h2 className="font-bold">Pending Assignment Reviews</h2><Link to="/teacher/assignments/review" className="text-sm font-semibold text-blue-600">Review all</Link></div>{d.reviews.slice(0,5).map(r=><div key={r.id} className="flex items-center gap-3 border-b p-4 last:border-0"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 font-bold text-slate-600">{(r.profiles?.full_name||"S").slice(0,1)}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{r.profiles?.full_name||"Student"}</p><p className="truncate text-xs text-slate-500">{r.assignments?.title||"Assignment"} · {fmtDate(r.submitted_at)}</p></div><Badge tone="amber">Pending</Badge></div>)}{!d.reviews.length&&<State type="empty" message="No pending assignments."/>}</Card>
   <Card><div className="border-b p-5"><h2 className="font-bold">Course Overview</h2></div>{d.courses.slice(0,5).map(c=><div key={c.id} className="flex items-center gap-4 border-b p-4 last:border-0"><div className="h-10 w-14 overflow-hidden rounded-lg bg-slate-100">{c.thumbnail&&<img src={c.thumbnail} className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{c.title}</p><p className="text-xs text-slate-500">{d.students.filter(s=>s.course_id===c.id).length} enrolled</p></div><Badge tone={c.status==="published"?"green":"slate"}>{c.status}</Badge></div>)}{!d.courses.length&&<State type="empty" message="No courses assigned yet."/>}</Card>
  </div>
 </TeacherPage>
}
