import { useCallback, useEffect, useState } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, CalendarDays, ClipboardList, FileText, Info, Send, UserRound } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { getAssignmentDetails, submitAssignment } from "../../services/studentService";
import { EmptyState, ErrorState, LoadingState, formatDate, formatDateTime } from "../../components/student/StudentDataState";

export default function AssignmentDetails() {
  const { id } = useParams();
  const [assignment, setAssignment] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [text, setText] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(null); try { const data = await getAssignmentDetails(id); setAssignment(data); setText(data?.submission?.submission_text || ""); } catch (err) { console.error(err); setError("We couldn't load this assignment right now."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  async function handleSubmit(e) { e.preventDefault(); setSaving(true); setMessage(""); try { await submitAssignment({ assignmentId: id, submissionText: text }); setMessage("Your submission was saved successfully."); await load(); } catch (err) { console.error(err); setMessage("We couldn't save your submission. Please try again."); } finally { setSaving(false); } }
  if (loading) return <LoadingState label="Loading assignment..." />;
  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!assignment) return <div className="flex min-h-[60vh] items-center justify-center"><EmptyState title="Assignment not found" description="The assignment you're looking for is unavailable." icon={ClipboardList} action={<Link to="/student/assignments" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><ArrowLeft size={16} />Back to Assignments</Link>} /></div>;
  const submission = assignment.submission;
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
    <Link to="/student/assignments" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={16} />Back to Assignments</Link>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase text-blue-700">{assignment.status}</span><h1 className="mt-3 text-2xl font-bold text-slate-950 sm:text-3xl">{assignment.title}</h1><div className="mt-3 flex flex-wrap gap-5 text-sm text-slate-500"><span className="inline-flex items-center gap-1.5"><BookIcon />{assignment.courses?.title || "Course"}</span><span className="inline-flex items-center gap-1.5"><UserRound size={15} />{assignment.teacher?.full_name || "Teacher"}</span><span className="inline-flex items-center gap-1.5"><CalendarDays size={15} />{formatDate(assignment.due_at)}</span></div></section>
    <section className="grid gap-6 lg:grid-cols-[1fr_340px]"><div className="space-y-6"><ContentCard title="Description" icon={FileText}><p className="text-sm leading-7 text-slate-600">{assignment.description || "No description provided."}</p></ContentCard><ContentCard title="Instructions" icon={Info}><p className="text-sm leading-7 text-slate-600 whitespace-pre-wrap">{assignment.instructions || "No additional instructions provided."}</p></ContentCard></div><aside className="space-y-6"><ContentCard title="Submission information" icon={ClipboardList}><dl className="space-y-3 text-sm"><InfoRow label="Status" value={submission?.status || "Not submitted"} /><InfoRow label="Submitted" value={formatDateTime(submission?.submitted_at)} /><InfoRow label="Marks" value={submission?.marks != null ? `${submission.marks} / ${assignment.max_marks}` : `— / ${assignment.max_marks}`} /></dl></ContentCard></aside></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="font-bold text-slate-950">Your submission</h2><p className="mt-1 text-sm text-slate-500">Submit your written response. File uploads require a separately configured Supabase Storage bucket.</p><form onSubmit={handleSubmit} className="mt-5 space-y-4"><textarea value={text} onChange={(e) => setText(e.target.value)} disabled={submission?.status === "graded" || saving} rows={8} placeholder="Write your answer here..." className="w-full rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm outline-none focus:border-blue-500 focus:bg-white" />{submission?.feedback && <div className="rounded-xl bg-emerald-50 p-4"><p className="text-xs font-bold uppercase text-emerald-700">Teacher feedback</p><p className="mt-1 whitespace-pre-wrap text-sm text-emerald-900">{submission.feedback}</p></div>}{message && <p className="text-sm font-semibold text-slate-600">{message}</p>}{submission?.status !== "graded" && <button disabled={saving || !text.trim()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"><Send size={16} />{saving ? "Saving..." : "Submit assignment"}</button>}</form></section>
  </motion.div>;
}
function BookIcon() { return <ClipboardList size={15} />; }
function InfoRow({ label, value }) { return <div className="flex items-start justify-between gap-4"><dt className="text-slate-400">{label}</dt><dd className="text-right font-semibold text-slate-700">{value}</dd></div>; }
function ContentCard({ title, icon: Icon, children }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={17} /></div><h2 className="font-bold text-slate-950">{title}</h2></div><div className="mt-5">{children}</div></section>; }
