import { useCallback, useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { ClipboardList, Search, CalendarDays, CheckCircle2 } from "lucide-react";
import { Link } from "react-router-dom";
import { getMyAssignments } from "../../services/studentService";
import { EmptyState, ErrorState, LoadingState, PageHeader, formatDate } from "../../components/student/StudentDataState";

const FILTERS = ["All", "Pending", "Submitted", "Graded", "Overdue"];
function statusFor(item) { if (item.submission?.status === "graded") return "Graded"; if (item.submission) return "Submitted"; if (item.due_at && new Date(item.due_at) < new Date()) return "Overdue"; return "Pending"; }
function Badge({ status }) { const cls = { Graded: "bg-emerald-50 text-emerald-700", Submitted: "bg-blue-50 text-blue-700", Overdue: "bg-red-50 text-red-700", Pending: "bg-amber-50 text-amber-700" }[status] || "bg-slate-100 text-slate-600"; return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${cls}`}>{status}</span>; }

export default function Assignments() {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await getMyAssignments()); } catch (err) { console.error(err); setError("We couldn't load your assignments right now."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => items.filter((item) => { const status = statusFor(item); const q = search.toLowerCase().trim(); return (filter === "All" || status === filter) && (!q || `${item.title} ${item.courses?.title || ""}`.toLowerCase().includes(q)); }), [items, filter, search]);
  const counts = useMemo(() => FILTERS.reduce((acc, f) => { acc[f] = f === "All" ? items.length : items.filter((x) => statusFor(x) === f).length; return acc; }, {}), [items]);
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
    <PageHeader eyebrow="Learning" title="Assignments" description="Track your coursework and stay on top of deadlines." />
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{FILTERS.map((f) => <button key={f} type="button" onClick={() => setFilter(f)} className={`rounded-2xl border p-4 text-left ${filter === f ? "border-blue-200 bg-blue-50" : "border-slate-200 bg-white"}`}><p className="text-xs font-semibold text-slate-500">{f}</p><p className="mt-1 text-xl font-bold text-slate-950">{counts[f] ?? 0}</p></button>)}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4"><label className="relative block max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search assignments..." className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-4 text-sm outline-none focus:border-blue-500 focus:bg-white" /></label></section>
    {loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : filtered.length ? <div className="space-y-3"><div className="hidden overflow-hidden rounded-2xl border border-slate-200 bg-white md:block"><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left"><thead className="bg-slate-50 text-xs font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Assignment</th><th className="px-5 py-4">Course</th><th className="px-5 py-4">Due Date</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Marks</th><th className="px-5 py-4">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => { const s = statusFor(item); return <tr key={item.id}><td className="px-5 py-4 font-semibold text-slate-900">{item.title}</td><td className="px-5 py-4 text-sm text-slate-500">{item.courses?.title || "—"}</td><td className="px-5 py-4 text-sm text-slate-500">{formatDate(item.due_at)}</td><td className="px-5 py-4"><Badge status={s} /></td><td className="px-5 py-4 text-sm font-semibold text-slate-700">{item.submission?.marks ?? "—"}{item.submission?.marks != null ? ` / ${item.max_marks}` : ""}</td><td className="px-5 py-4"><Link to={`/student/assignments/${item.id}`} className="text-sm font-semibold text-blue-600">View</Link></td></tr>; })}</tbody></table></div></div><div className="space-y-3 md:hidden">{filtered.map((item) => <Link key={item.id} to={`/student/assignments/${item.id}`} className="block rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-slate-900">{item.title}</h3><p className="mt-1 text-xs text-slate-500">{item.courses?.title || "—"}</p></div><Badge status={statusFor(item)} /></div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span className="inline-flex items-center gap-1.5"><CalendarDays size={14} />{formatDate(item.due_at)}</span><span>{item.submission?.marks ?? "—"}{item.submission?.marks != null ? ` / ${item.max_marks}` : ""}</span></div></Link>)}</div></div> : <EmptyState title="No assignments yet" description="You don't have any assignments assigned to you." icon={ClipboardList} action={(filter !== "All" || search) ? <button type="button" onClick={() => { setFilter("All"); setSearch(""); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700"><CheckCircle2 size={16} />Clear filters</button> : null} />}
  </motion.div>;
}
