import { useCallback, useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Download, FileText, FolderOpen, Search } from "lucide-react";
import { getMyCourses, getStudyMaterials } from "../../services/studentService";
import { EmptyState, ErrorState, LoadingState, PageHeader, formatDate } from "../../components/student/StudentDataState";

const FILTERS = ["All", "PDF", "Slides", "Notes", "Resources", "Assignments"];
function MaterialCard({ material }) {
  const fileAvailable = Boolean(material.file_path);
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 transition hover:border-blue-200 hover:shadow-md"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><FileText size={20} /></div><div className="min-w-0 flex-1"><span className="text-[10px] font-bold uppercase tracking-wider text-blue-600">{material.type}</span><h3 className="mt-1 text-sm font-bold text-slate-950">{material.title}</h3><p className="mt-1 text-xs font-medium text-slate-500">{material.courses?.title || "Course"}</p></div></div>{material.description && <p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-500">{material.description}</p>}<div className="mt-5 flex items-center justify-between gap-3 text-xs"><span className="text-slate-400">{formatDate(material.created_at)}{material.file_size ? ` · ${Math.round(material.file_size / 1024)} KB` : ""}</span>{fileAvailable ? <span className="font-semibold text-blue-600"><Download size={14} className="inline" /> File ready</span> : <span className="font-semibold text-slate-400">File unavailable</span>}</div></article>;
}

export default function StudyMaterials() {
  const [materials, setMaterials] = useState([]); const [courses, setCourses] = useState([]); const [filter, setFilter] = useState("All"); const [search, setSearch] = useState(""); const [courseId, setCourseId] = useState("All"); const [loading, setLoading] = useState(true); const [error, setError] = useState(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [m, c] = await Promise.all([getStudyMaterials(), getMyCourses()]); setMaterials(m); setCourses(c); } catch (err) { console.error(err); setError("We couldn't load your study materials right now."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => materials.filter((m) => (filter === "All" || m.type === filter) && (courseId === "All" || m.course_id === courseId) && (!search.trim() || `${m.title} ${m.description || ""} ${m.courses?.title || ""}`.toLowerCase().includes(search.trim().toLowerCase()))), [materials, filter, courseId, search]);
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6"><PageHeader eyebrow="Learning" title="Study Materials" description="Access your course resources and keep your learning organized." /><section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap gap-2">{FILTERS.map((f) => <button key={f} type="button" onClick={() => setFilter(f)} className={`rounded-xl px-3.5 py-2 text-xs font-semibold ${filter === f ? "bg-blue-600 text-white" : "bg-slate-50 text-slate-600"}`}>{f}</button>)}</div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_220px]"><label className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search study materials..." className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-4 text-sm outline-none focus:border-blue-500 focus:bg-white" /></label><select value={courseId} onChange={(e) => setCourseId(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-blue-500"><option value="All">All courses</option>{courses.map((c) => <option key={c.course_id} value={c.course_id}>{c.courses?.title || "Course"}</option>)}</select></div></section>{loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : filtered.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((m) => <MaterialCard key={m.id} material={m} />)}</div> : <EmptyState title="No study materials yet" description="Your course resources will appear here when they are available." icon={FolderOpen} />}</motion.div>;
}
