import { Link } from "react-router-dom";
import { BookOpen, BriefcaseBusiness, CalendarDays, CreditCard, FileBadge, GraduationCap, TrendingUp, Users, UserPlus, Video, ArrowUpRight, CheckCircle2 } from "lucide-react";
import { getDashboardData } from "../../services/managerService";
import { Card, ErrorState, formatDateTime, LoadingState, PageHeader, StatCard, StatusBadge, useManagerData, money } from "../../components/manager/ManagerUI";
import { useAuth } from "../../context/AuthContext";

const recent = (data) => {
 const events=[];
 (data.enrollments||[]).slice().sort((a,b)=>new Date(b.enrolled_at)-new Date(a.enrolled_at)).slice(0,4).forEach(x=>events.push({label:"Course enrollment",date:x.enrolled_at,detail:x.status}));
 (data.payments||[]).slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,3).forEach(x=>events.push({label:"Payment activity",date:x.created_at,detail:money(x.amount,x.currency)}));
 (data.certificates||[]).slice().sort((a,b)=>new Date(b.issued_at)-new Date(a.issued_at)).slice(0,3).forEach(x=>events.push({label:"Certificate issued",date:x.issued_at,detail:x.certificate_number}));
 (data.schedules||[]).slice().sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,3).forEach(x=>events.push({label:"Class scheduled",date:x.created_at,detail:x.title}));
 return events.sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,8);
};

export default function Dashboard(){
 const {profile,user}=useAuth(); const {data,error,loading,reload}=useManagerData(getDashboardData);
 const name=profile?.full_name||user?.user_metadata?.full_name||"Manager";
 if(loading)return <LoadingState text="Loading manager overview…"/>; if(error)return <ErrorState onRetry={reload}/>;
 const d=data; const pendingPayments=d.payments.filter(x=>x.status==="pending").length; const revenue=d.payments.filter(x=>x.status==="paid").reduce((s,x)=>s+Number(x.amount||0),0); const today=d.schedules.filter(x=>new Date(x.starts_at).toDateString()===new Date().toDateString()).length;
 const stats=[["Total Students",d.students.length,Users,"blue"],["Total Teachers",d.teachers.length,GraduationCap,"violet"],["Active Courses",d.courses.filter(x=>x.status==="published").length,BookOpen,"green"],["Pending Admissions",0,UserPlus,"amber"],["Today's Classes",today,Video,"blue"],["Pending Payments",pendingPayments,CreditCard,"amber"],["Certificates Issued",d.certificates.length,FileBadge,"green"],["Active Internships",d.internships.filter(x=>x.status==="open").length,BriefcaseBusiness,"violet"]];
 const completion=d.enrollments.length?Math.round(d.enrollments.reduce((s,x)=>s+Number(x.progress||0),0)/d.enrollments.length):0;
 return <div><PageHeader title={`Good morning, ${name} 👋`} description="Here's your education platform overview." action={<button onClick={reload} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold hover:bg-slate-50">Refresh</button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([l,v,I,t])=><StatCard key={l} label={l} value={v} icon={I} tone={t}/>)}</div>
 <div className="mt-6 grid gap-6 xl:grid-cols-3"><Card className="p-6 xl:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Platform health</h2><p className="mt-1 text-sm text-slate-500">Live indicators from your current database.</p></div><TrendingUp className="text-blue-600" size={20}/></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Enrollment progress" value={`${completion}%`} pct={completion}/><Metric label="Paid revenue" value={money(revenue,"PKR")} pct={d.payments.length?Math.round(d.payments.filter(x=>x.status==="paid").length/d.payments.length*100):0}/><Metric label="Attendance coverage" value={`${d.attendance.length} records`} pct={Math.min(100,d.attendance.length?70:0)}/></div></Card><Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold">Quick actions</h2><p className="mt-1 text-sm text-slate-500">Jump to common operations.</p></div></div><div className="mt-5 grid gap-2">{[["New Admission","/manager/admissions",UserPlus],["Add Student","/manager/students",Users],["Add Teacher","/manager/teachers",GraduationCap],["Create Course","/manager/courses",BookOpen],["Schedule Class","/manager/schedules",CalendarDays],["Issue Certificate","/manager/certificates",FileBadge]].map(([l,p,I])=><Link key={p} to={p} className="flex items-center justify-between rounded-xl border border-slate-100 px-3 py-2.5 text-sm font-semibold hover:border-blue-200 hover:bg-blue-50"><span className="flex items-center gap-3"><I size={17} className="text-blue-600"/>{l}</span><ArrowUpRight size={16} className="text-slate-400"/></Link>)}</div></Card></div>
 <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card className="p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Recent activity</h2><Link to="/manager/analytics" className="text-sm font-semibold text-blue-600">View analytics</Link></div><div className="mt-5 space-y-4">{recent(d).length?recent(d).map((x,i)=><div key={i} className="flex gap-3"><div className="mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-50 text-blue-600"><CheckCircle2 size={16}/></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-800">{x.label}</p><p className="truncate text-xs text-slate-500">{x.detail} · {formatDateTime(x.date)}</p></div></div>):<p className="py-8 text-sm text-slate-500">No recent activity found.</p>}</div></Card><Card className="p-6"><h2 className="font-bold">Operational snapshot</h2><div className="mt-5 space-y-4">{[["Published courses",d.courses.filter(x=>x.status==="published").length,d.courses.length],["Active enrollments",d.enrollments.filter(x=>x.status==="active").length,d.enrollments.length],["Completed enrollments",d.enrollments.filter(x=>x.status==="completed").length,d.enrollments.length],["Open internships",d.internships.filter(x=>x.status==="open").length,d.internships.length]].map(([l,v,total])=><div key={l}><div className="flex justify-between text-sm"><span className="font-medium text-slate-600">{l}</span><span className="font-bold text-slate-900">{v}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{width:`${total?Math.min(100,v/total*100):0}%`}}/></div></div>)}</div></Card></div>
 </div>
}
function Metric({label,value,pct}){return <div className="rounded-xl border border-slate-100 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-bold">{value}</p><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{width:`${pct}%`}}/></div></div>}
