import { useEffect, useMemo, useState } from "react";
import { MessageSquare, Send, Search } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { getAllMessages, getAllUsers, markMessageRead, sendMessage } from "../../services/managerService";
import { ErrorState, LoadingState, PageHeader } from "../../components/manager/ManagerUI";

export default function Messages(){
 const {user}=useAuth(); const [data,setData]=useState(null);const [active,setActive]=useState(null);const [body,setBody]=useState("");const [q,setQ]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [sending,setSending]=useState(false);
 const load=async()=>{setLoading(true);setError("");try{const [users,messages]=await Promise.all([getAllUsers(),getAllMessages()]);setData({users,messages})}catch(e){console.error(e);setError(e.message||"Unable to load all messages. Apply the Manager operations SQL migration.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const users=useMemo(()=>{if(!data)return[];return data.users.filter(p=>p.id!==user?.id&&`${p.full_name||""} ${p.email||""}`.toLowerCase().includes(q.toLowerCase()))},[data,q,user?.id]);
 const selected=data?.users.find(p=>p.id===active)||users[0];
 const conversation=useMemo(()=>selected&&data?data.messages.filter(m=>(m.sender_id===user?.id&&m.recipient_id===selected.id)||(m.sender_id===selected.id&&m.recipient_id===user?.id)).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)):[],[data,selected,user?.id]);
 useEffect(()=>{conversation.filter(m=>m.recipient_id===user?.id&&!m.read_at).forEach(m=>markMessageRead(m.id).catch(()=>{}))},[conversation,user?.id]);
 if(loading)return <LoadingState/>;if(error)return <ErrorState message={error} onRetry={load}/>;
 const send=async(e)=>{e?.preventDefault();if(!body.trim()||!selected)return;setSending(true);try{await sendMessage({sender_id:user.id,recipient_id:selected.id,body:body.trim()});setBody("");await load()}catch(e){setError(e.message||"Message could not be sent.")}finally{setSending(false)}};
 return <><PageHeader title="Messages" description="Managers can see and message every user account, not only users with an existing conversation." icon={MessageSquare}/>
 <div className="grid min-h-[650px] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm md:grid-cols-[300px_1fr]">
  <aside className="border-b md:border-b-0 md:border-r"><div className="border-b p-4"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search any user..." className="h-10 w-full rounded-xl border pl-9 pr-3 text-sm"/></div><p className="mt-3 text-xs text-slate-400">{users.length} user{users.length===1?"":"s"}</p></div><div className="max-h-[570px] overflow-y-auto">{users.map(p=><button key={p.id} onClick={()=>setActive(p.id)} className={`w-full border-b border-slate-100 p-4 text-left ${selected?.id===p.id?"bg-blue-50":"hover:bg-slate-50"}`}><p className="truncate text-sm font-semibold">{p.full_name||"Unnamed user"}</p><p className="truncate text-xs text-slate-400">{p.email||p.phone||p.id}</p></button>)}</div></aside>
  <section className="flex min-h-[650px] flex-col">{selected?<><div className="border-b p-4"><p className="font-bold">{selected.full_name||"User"}</p><p className="text-xs text-slate-400">{selected.email||""}</p></div><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-5">{conversation.map(m=><div key={m.id} className={`flex ${m.sender_id===user.id?"justify-end":""}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm ${m.sender_id===user.id?"bg-blue-600 text-white":"bg-white text-slate-800 shadow-sm"}`}><p>{m.body}</p><p className={`mt-1 text-[10px] ${m.sender_id===user.id?"text-blue-100":"text-slate-400"}`}>{new Date(m.created_at).toLocaleString()}</p></div></div>)}{!conversation.length&&<div className="flex h-full items-center justify-center text-sm text-slate-400">No messages yet. Start the conversation.</div>}</div><form onSubmit={send} className="border-t p-4"><div className="flex gap-2"><input value={body} onChange={e=>setBody(e.target.value)} placeholder={`Message ${selected.full_name||"user"}…`} className="min-w-0 flex-1 rounded-xl border px-4 py-3 text-sm outline-none focus:border-blue-500"/><button disabled={sending||!body.trim()} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><Send size={16}/>Send</button></div></form></>:<div className="flex flex-1 items-center justify-center text-slate-400">Select a user.</div>}</section>
 </div></>;
}
