import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { AlertCircle, CheckCircle2, Loader2, Search, X, ChevronDown, Plus, RefreshCw } from "lucide-react";

export function PageHeader({ title, description, action, icon: Icon }) {
  return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-3">{Icon && <div className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Icon size={20}/></div>}<h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{title}</h1></div>{description && <p className="mt-2 max-w-3xl text-sm text-slate-500">{description}</p>}</div>{action}</div>;
}
export function Card({ children, className="" }) { return <div className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>; }
export function StatCard({ label, value, icon: Icon, tone="blue", hint }) { const tones={blue:"bg-blue-50 text-blue-600",green:"bg-emerald-50 text-emerald-600",amber:"bg-amber-50 text-amber-600",red:"bg-red-50 text-red-600",violet:"bg-violet-50 text-violet-600"}; return <Card className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p>{hint&&<p className="mt-1 text-xs text-slate-400">{hint}</p>}</div>{Icon&&<div className={`rounded-xl p-3 ${tones[tone]||tones.blue}`}><Icon size={20}/></div>}</div></Card>; }
export function LoadingState({ text="Loading data…" }) { return <div className="flex min-h-[280px] items-center justify-center"><div className="flex items-center gap-3 text-sm font-medium text-slate-500"><Loader2 className="animate-spin" size={20}/>{text}</div></div>; }
export function ErrorState({ onRetry, message="We couldn't load this data right now." }) { return <div className="flex min-h-[280px] items-center justify-center"><div className="max-w-md text-center"><AlertCircle className="mx-auto text-red-500" size={32}/><h3 className="mt-3 font-semibold text-slate-900">Something went wrong</h3><p className="mt-1 text-sm text-slate-500">{message}</p>{onRetry&&<button onClick={onRetry} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white"><RefreshCw size={15}/>Try again</button>}</div></div>; }
export function EmptyState({ title="Nothing here yet", description="No records match the current view." }) { return <div className="py-14 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-slate-400"><Search size={20}/></div><h3 className="mt-3 font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div>; }
export function BackendState({ title, description, sql }) { return <Card className="p-6"><div className="flex gap-3"><div className="rounded-xl bg-amber-50 p-2 text-amber-600"><AlertCircle size={20}/></div><div><h3 className="font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p>{sql&&<pre className="mt-4 overflow-x-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-200">{sql}</pre>}</div></div></Card>; }
export function StatusBadge({ status }) { const s=String(status||"unknown").toLowerCase(); const map={paid:"bg-emerald-50 text-emerald-700",active:"bg-emerald-50 text-emerald-700",published:"bg-emerald-50 text-emerald-700",open:"bg-emerald-50 text-emerald-700",completed:"bg-blue-50 text-blue-700",pending:"bg-amber-50 text-amber-700",scheduled:"bg-blue-50 text-blue-700",live:"bg-red-50 text-red-700",failed:"bg-red-50 text-red-700",rejected:"bg-red-50 text-red-700",cancelled:"bg-slate-100 text-slate-600",draft:"bg-slate-100 text-slate-600",refunded:"bg-violet-50 text-violet-700",qualified:"bg-blue-50 text-blue-700",rewarded:"bg-emerald-50 text-emerald-700"}; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${map[s]||"bg-slate-100 text-slate-600"}`}>{s}</span>; }
export function Toolbar({ search, setSearch, filters=[], value, setValue, children }) { return <div className="mb-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="flex flex-1 flex-col gap-2 sm:flex-row"><div className="relative max-w-md flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search…" className="h-10 w-full rounded-xl border border-slate-200 bg-white pl-9 pr-3 text-sm outline-none focus:border-blue-500"/></div>{filters.map(f=><div className="relative" key={f.key}><select value={value[f.key]||""} onChange={e=>setValue(v=>({...v,[f.key]:e.target.value}))} className="h-10 appearance-none rounded-xl border border-slate-200 bg-white pl-3 pr-9 text-sm outline-none"><option value="">{f.label}</option>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3 text-slate-400"/></div>)}</div>{children}</div>; }
export function Table({ columns, rows, keyField="id", empty="No records found." }) { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr>{columns.map(c=><th key={c.key} className="whitespace-nowrap px-4 py-3 font-semibold">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.length?rows.map((row,i)=><motion.tr initial={{opacity:0}} animate={{opacity:1}} key={row[keyField]||i} className="hover:bg-slate-50">{columns.map(c=><td key={c.key} className="whitespace-nowrap px-4 py-3 text-slate-700">{c.render?c.render(row):row[c.key]??"—"}</td>)}</motion.tr>):<tr><td colSpan={columns.length}><EmptyState description={empty}/></td></tr>}</tbody></table></div></div>; }
export function useManagerData(loader, deps=[]) { const [state,setState]=useState({loading:true,error:null,data:null}); const load=async()=>{setState(s=>({...s,loading:true,error:null}));try{setState({loading:false,error:null,data:await loader()})}catch(e){console.error(e);setState({loading:false,error:e,data:null})}};useEffect(()=>{load()},deps);return {...state,reload:load}; }
export function ConfirmDialog({ open, title, description, confirmLabel="Confirm", danger=false, onConfirm, onClose, busy=false }) { if(!open)return null; return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-lg font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{description}</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18}/></button></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={busy} onClick={onConfirm} className={`rounded-xl px-4 py-2 text-sm font-semibold text-white ${danger?"bg-red-600":"bg-blue-600"}`}>{busy?<Loader2 size={16} className="animate-spin"/>:confirmLabel}</button></div></div></div>; }
export function formatDate(value) { if(!value)return "—"; const d=new Date(value); return Number.isNaN(d.getTime())?"—":d.toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric"}); }
export function formatDateTime(value) { if(!value)return "—"; const d=new Date(value); return Number.isNaN(d.getTime())?"—":d.toLocaleString(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}); }
export function money(amount,currency="PKR") { return new Intl.NumberFormat(undefined,{style:"currency",currency}).format(Number(amount||0)); }
