import { useState } from "react";
import { NavLink, Outlet, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import ThemeToggle from "../components/common/ThemeToggle";
import { LayoutDashboard, Users, ShieldCheck, KeyRound, BookOpen, FolderTree, Building2, Layers3, FileText, ClipboardList, GraduationCap, Award, BriefcaseBusiness, CalendarCheck, Video, CreditCard, ShoppingCart, Receipt, Store, Package, BarChart3, FileBarChart, ScrollText, Newspaper, Image, Globe2, Bot, LockKeyhole, Settings, UserCircle, LogOut, Menu, X, Search, Bell, MessageSquare, ChevronDown, PanelLeftClose, PanelLeftOpen } from "lucide-react";

const groups=[
 ["Dashboard", [["Dashboard","/admin/dashboard",LayoutDashboard]]],
 ["User Management",[["Users","/admin/users",Users],["Admissions","/admin/admissions",GraduationCap],["Roles","/admin/roles",ShieldCheck],["Permissions","/admin/permissions",KeyRound]]],
 ["Academic",[["Courses","/admin/courses",BookOpen],["Categories","/admin/categories",FolderTree],["Departments","/admin/departments",Building2],["Modules","/admin/modules",Layers3],["Lessons","/admin/lessons",FileText],["Quizzes","/admin/quizzes",ClipboardList],["Assignments","/admin/assignments",ClipboardList],["Exams","/admin/exams",GraduationCap]]],
 ["Student Services",[["Meetings","/admin/meetings",Video],["Certificates","/admin/certificates",Award],["Internships","/admin/internships",BriefcaseBusiness],["Attendance","/admin/attendance",CalendarCheck],["Live Classes","/admin/live-classes",Video]]],
 ["Finance",[["Payments","/admin/payments",CreditCard],["Orders","/admin/orders",ShoppingCart],["Invoices","/admin/invoices",Receipt]]],
 ["Marketplace",[["Products","/admin/products",Package],["Marketplace","/admin/marketplace",Store]]],
 ["Analytics",[["Analytics","/admin/analytics",BarChart3],["Reports","/admin/reports",FileBarChart],["Audit Logs","/admin/audit-logs",ScrollText]]],
 ["Content",[["Blog","/admin/blog",Newspaper],["Media Library","/admin/media-library",Image],["Website","/admin/website",Globe2]]],
 ["System",[["AI Settings","/admin/ai-settings",Bot],["Security","/admin/security",LockKeyhole],["System Settings","/admin/system-settings",Settings]]],
 ["Account",[["Profile","/admin/profile",UserCircle]]],
];
export default function AdminLayout(){
 const [open,setOpen]=useState(false),[collapsed,setCollapsed]=useState(false);const {user,profile,role,signOut}=useAuth();const nav=useNavigate();
 const name=profile?.full_name||user?.user_metadata?.full_name||"Admin";const initials=name.split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"AD";
 const logout=async()=>{await signOut();nav("/login",{replace:true})};
 return <div className="admin-portal min-h-screen bg-[var(--background)] text-[var(--foreground)]">
  {open&&<button aria-label="Close navigation" onClick={()=>setOpen(false)} className="fixed inset-0 z-40 bg-slate-950/50 lg:hidden"/>}
  <aside className={`fixed inset-y-0 left-0 z-50 flex flex-col border-r border-[var(--sidebar-border)] bg-[var(--sidebar)] text-white transition-all duration-200 ${collapsed?"w-[82px]":"w-[276px]"} ${open?"translate-x-0":"-translate-x-full lg:translate-x-0"}`}>
   <div className="flex h-16 shrink-0 items-center justify-between border-b border-[var(--sidebar-border)] px-4"><div className="flex items-center gap-3 overflow-hidden"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-blue-600"><GraduationCap size={20}/></div>{!collapsed&&<div><p className="font-bold">EduVerse</p><p className="text-[10px] uppercase tracking-widest text-[var(--muted)]">Admin Control Center</p></div>}</div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 lg:hidden"><X size={18}/></button></div>
   <nav className="flex-1 overflow-y-auto px-3 py-4">{groups.map(([title,items])=><div key={title} className="mb-5">{!collapsed&&<p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.15em] text-[var(--muted)]">{title}</p>}<div className="space-y-1">{items.map(([label,path,I])=><NavLink key={path} title={collapsed?label:undefined} to={path} end={path==="/admin/dashboard"} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center ${collapsed?"justify-center":"gap-3"} rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive?"bg-blue-600 text-white":"text-slate-400 hover:bg-slate-900 hover:text-white"}`}><I size={18}/>{!collapsed&&<span>{label}</span>}</NavLink>)}</div></div>)}</nav>
   <div className="border-t border-[var(--sidebar-border)] p-3">{!collapsed&&<button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-400 hover:bg-red-500/10 hover:text-red-300"><LogOut size={18}/>Logout</button>} {collapsed&&<button onClick={logout} title="Logout" className="flex w-full justify-center rounded-xl p-2.5 text-slate-400 hover:bg-red-500/10 hover:text-red-300"><LogOut size={18}/></button>}</div>
  </aside>
  <div className={collapsed?"lg:pl-[82px]":"lg:pl-[276px]"}><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[var(--border)] bg-[var(--card)]/95 px-4 backdrop-blur sm:px-6"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setOpen(true)} className="rounded-xl p-2 text-[var(--muted)] hover:bg-[var(--surface-hover)] lg:hidden"><Menu size={21}/></button><button onClick={()=>setCollapsed(v=>!v)} className="hidden rounded-xl p-2 text-[var(--muted)] hover:bg-[var(--surface-hover)] lg:block" title="Toggle sidebar">{collapsed?<PanelLeftOpen size={19}/>:<PanelLeftClose size={19}/>}</button><div className="relative hidden md:block"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input placeholder="Search platform…" className="h-10 w-72 rounded-xl border border-[var(--border)] bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:bg-white"/></div><span className="font-semibold md:hidden">Admin Portal</span></div><div className="flex items-center gap-1 sm:gap-2"><ThemeToggle compact /><button className="rounded-xl p-2.5 text-[var(--muted)] hover:bg-[var(--surface-hover)]" title="Messages"><MessageSquare size={18}/></button><button className="relative rounded-xl p-2.5 text-[var(--muted)] hover:bg-[var(--surface-hover)]" title="Notifications"><Bell size={18}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-blue-600 ring-2 ring-white"/></button><div className="ml-1 h-7 w-px bg-slate-200"/><NavLink to="/admin/profile" className="flex items-center gap-2 rounded-xl px-2 py-1.5 hover:bg-slate-50"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-600 text-xs font-bold text-white">{initials}</div><div className="hidden text-left sm:block"><p className="max-w-[130px] truncate text-sm font-semibold">{name}</p><p className="text-[11px] text-[var(--muted)]">{role||"Admin"}</p></div><ChevronDown size={15} className="hidden text-slate-400 sm:block"/></NavLink></div></header><main className="min-h-[calc(100vh-64px)]"><div className="mx-auto w-full max-w-[1700px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><Outlet/></div></main></div>
 </div>
}
