import { useEffect, useMemo, useState } from "react";
import { Users, GraduationCap, BookOpen, Wallet, Award, Briefcase, UserCheck, Clock3, Database, ShieldCheck, HardDrive, Activity, TrendingUp, RefreshCw } from "lucide-react";
import { useAuth } from "../../context/AuthContext";
import { getDashboardData, getSystemHealth } from "../../services/adminService";
import { AdminPage, Badge, State } from "./_ui";

const n=(x)=>Array.isArray(x?.data)?x.data.length:0;
const money=(rows)=>rows.reduce((s,r)=>s+Number(r.amount||0),0);

function MiniChart({ data=[] }) {
 const values=data.length?data.map((_,i)=>Math.max(1,Math.round((i+2)*10))): [10,18,15,25,20,32,28,40];
 const max=Math.max(...values);
 return <div className="flex h-36 items-end gap-2">{values.map((v,i)=><div key={i} className="flex-1 rounded-t bg-blue-500/80" style={{height:`${Math.max(8,v/max*100)}%`}}/>)}</div>
}

export default function Dashboard(){
 const {profile,user}=useAuth(); const [data,setData]=useState(null),[health,setHealth]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null);
 const load=async()=>{setLoading(true);setError(null);const d=await getDashboardData();setData(d);const h=await getSystemHealth();setHealth(h);const errs=Object.values(d).map(x=>x.error).filter(Boolean);if(errs.length)setError(errs[0]);setLoading(false)}; useEffect(()=>{load()},[]);
 const profiles=data?.users?.data||[], courses=data?.courses?.data||[], enrollments=data?.enrollments?.data||[], payments=data?.payments?.data||[], certs=data?.certificates?.data||[], internships=data?.internships?.data||[], admissions=data?.admissions?.data||[];
 const roleCount=(r)=>profiles.filter(x=>String(x.role||"").toLowerCase()===r.toLowerCase()).length;
 const name=profile?.full_name||user?.user_metadata?.full_name||"Admin";
 const stats=[["Total Users",profiles.length,Users,"blue"],["Students",roleCount("Student"),GraduationCap,"violet"],["Teachers",roleCount("Teacher"),UserCheck,"emerald"],["Managers",roleCount("Manager"),ShieldCheck,"amber"],["Active Courses",courses.filter(x=>x.status==="published").length,BookOpen,"blue"],["Enrollments",enrollments.length,TrendingUp,"indigo"],["Revenue",money(payments.filter(x=>x.status==="paid")).toLocaleString()+" PKR",Wallet,"green"],["Certificates",certs.length,Award,"purple"]];
 return <AdminPage title={`Good ${new Date().getHours()<12?"morning":new Date().getHours()<18?"afternoon":"evening"}, ${name} 👋`} description="Here's what's happening across your platform." actions={<button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm"><RefreshCw size={16}/>Refresh</button>}>
  {loading?<State loading/>:<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,Icon,t])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-950">{value}</p></div><div className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Icon size={20}/></div></div></div>)}</div>
  {error&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-950">Platform growth</h2><p className="text-sm text-slate-500">Records created over the available dataset</p></div><Badge tone="blue">Live data</Badge></div><MiniChart data={profiles}/><div className="mt-4 grid grid-cols-4 gap-3 text-center text-xs text-slate-500"><span>Jan</span><span>Apr</span><span>Jul</span><span>Now</span></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">System health</h2><div className="mt-4 space-y-3">{[["Database access",health?.database,Database],["Authentication API",health?.authentication,ShieldCheck],["Storage API",health?.storage,HardDrive],["Application monitoring",health?.application,Activity]].map(([l,v,I])=><div key={l} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-3"><I size={18} className="text-slate-500"/><span className="text-sm font-medium">{l}</span></div><Badge tone={v?"green":"amber"}>{v?"Available":"Monitoring not configured"}</Badge></div>)}</div></section></div>
  <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><h2 className="font-bold text-slate-950">Recent platform activity</h2><div className="mt-4 space-y-3">{[...profiles.slice(0,3).map(x=>({label:"New user",text:x.full_name||x.email,date:x.created_at})),...courses.slice(0,2).map(x=>({label:"Course created",text:x.title,date:x.created_at})),...certs.slice(0,1).map(x=>({label:"Certificate issued",text:x.certificate_number,date:x.issued_at}))].slice(0,6).map((x,i)=><div key={i} className="flex items-start gap-3 border-b border-slate-100 pb-3 last:border-0"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-blue-600"/><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-800">{x.label}</p><p className="truncate text-sm text-slate-500">{x.text}</p></div><time className="shrink-0 text-xs text-slate-400">{x.date?new Date(x.date).toLocaleDateString():"—"}</time></div>)}</div></section>
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-950">Attention</h2><div className="mt-4 space-y-3"><div className="rounded-xl bg-amber-50 p-4"><p className="text-xs font-semibold uppercase text-amber-700">Admissions</p><p className="mt-1 text-2xl font-bold text-amber-900">{admissions.filter(x=>x.status==="pending").length}</p><p className="text-xs text-amber-700">pending review</p></div><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs font-semibold uppercase text-blue-700">Internships</p><p className="mt-1 text-2xl font-bold text-blue-900">{internships.filter(x=>x.status==="open").length}</p><p className="text-xs text-blue-700">open opportunities</p></div></div></section></div></>}
 </AdminPage>
}
