import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw, Users as UsersIcon } from "lucide-react";
import { getUsers } from "../../services/adminService";
import CreateUserModal from "../../components/common/CreateUserModal";
import { AdminPage, AdminTable, Badge, State, Toolbar } from "./_ui";
export default function Users(){const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(null),[search,setSearch]=useState(""),[role,setRole]=useState(""),[createOpen,setCreateOpen]=useState(false);
const load=async()=>{setLoading(true);const r=await getUsers();setRows(r.data||[]);setError(r.error);setLoading(false)};useEffect(()=>{load()},[]);
const filtered=useMemo(()=>rows.filter(r=>(!role||r.role===role)&&(!search||[r.full_name,r.email,r.role].some(v=>String(v||"").toLowerCase().includes(search.toLowerCase())))),[rows,role,search]);
return <><AdminPage title="Users" description="Manage real authenticated users and their platform access." icon={UsersIcon} actions={<div className="flex gap-2"><button onClick={load} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600"><RefreshCw size={17}/></button><button onClick={()=>setCreateOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/>Add user</button></div>}><Toolbar search={search} setSearch={setSearch} filters={<select value={role} onChange={e=>setRole(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All roles</option>{["Admin","Manager","Teacher","Student","Unassigned"].map(x=><option key={x}>{x}</option>)}</select>}/><State loading={loading} error={error} empty={!filtered.length}/>{!loading&&filtered.length>0&&<AdminTable columns={[{key:"full_name",label:"User",render:r=><div><p className="font-semibold text-slate-800">{r.full_name||"Unnamed"}</p><p className="text-xs text-slate-400">{r.id}</p></div>},{key:"email",label:"Email"},{key:"role",label:"Role",render:r=><Badge tone={r.role==="Admin"?"blue":"slate"}>{r.role}</Badge>},{key:"created_at",label:"Created",render:r=>r.created_at?new Date(r.created_at).toLocaleDateString():"—"},{key:"status",label:"Status",render:()=> <Badge tone="green">Active</Badge>}] } rows={filtered}/>}</AdminPage><CreateUserModal open={createOpen} onClose={()=>setCreateOpen(false)} onCreated={load}/></>}
